name: blowout-api-server
version: '0.1' 
summary: API server for maintaining the state of a blowout counter.
description: |
  Endpoint to get information in json: http://hostip:9999/api/info
  Endpoint to increment by 1: http://hostip:9999/api/add
  When server reaches 100, a blowout is triggerd
  
  Author: Erik Lonroth erik.lonroth@gmail.com

grade: devel # must be 'stable' to release into candidate/stable channels

confinement: devmode # use 'strict' once you have the right plugs and slots


apps:
  flask-nginx:
    command: wrappers/flask-nginx
    daemon: simple
    plugs: [network, network-bind]
  nginx:
    command: wrappers/nginx-wrap
    daemon: simple
    plugs: [network, network-bind]


parts:
  flask-nginx:
    plugin: python
    source: https://github.com/erik78se/blowout-api-server.git 
    source-type: git
    python-version: python3
    requirements: requirements.txt
    python-packages: [gunicorn]
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/flask-app
      cp -r ./* $SNAPCRAFT_PART_INSTALL/flask-app/
  wrappers:
    plugin: dump
    source: snap/
  nginx:
    plugin: nginx
    source: .
    install: |
      rm $SNAPCRAFT_PART_INSTALL/nginx/conf/nginx.conf.default
      rm $SNAPCRAFT_PART_INSTALL/nginx/conf/nginx.conf
      sed 's|_SNAPNAME_|blowout-api-server|g' nginx.conf.snap.template > $SNAPCRAFT_PART_INSTALL/nginx/conf/nginx.conf
      cp ./nginx.proxy_params.snap.template $SNAPCRAFT_PART_INSTALL/nginx/conf/proxy_params
